### PR TITLE
Fix accepting of unicode arguments by pr-downloade binary

### LINKED ISSUE #16: CFileSystem::getMBsFree "still" seems to fail when the path contains non-ASCII characters
I reported this issue back in April on spring's pr-downloader https://github.com/spring/pr-downloader/issues/145 and it is supposed to have been fixed https://github.com/spring/pr-downloader/issues/145 in there and ported to BAR's pr-downloader as well https://github.com/beyond-all-reason/pr-downloader/commit/34cf14ad65c1ac79b2ed3886ff9e778df595c98d. However, a user reported the same issue today so it doesn't seem to have been actually fixed.

### PR DESCRIPTION
**Pull request by p2004a**
On Windows the regular argv is encoded in a very basic non-unicode codepage. This change properly reads them as unicode strings instead and encodes them as utf-8 into argv.

Fixes #16

(Making the PR as WIP for now as I want to test a bit more)

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -107,8 +112,30 @@ bool download(DownloadEnum::Category cat, const char* name)
 	return true;
 }
 
+#ifdef _WIN32
+
+static std::vector<std::string> argv_strings;
+static std::vector<const char*> argv_data;
```
Comment (rafidka) [inline src/main.cpp:118]: Why are these two defined globally? They are only used in the `prepare_args` function, so I would just define them there (as static obviously, so they don't get deallocated, causing segmentation fault.)

File: src/main.cpp [hunk 2]
```diff
@@ -107,8 +112,30 @@ bool download(DownloadEnum::Category cat, const char* name)
...
+
+void prepare_args(int *argc, char*** argv) {
+	wchar_t** argv_w = CommandLineToArgvW(GetCommandLineW(), argc);
```
Comment (rafidka) [inline src/main.cpp:121]: Keep this in mind:

> CommandLineToArgvW allocates a block of contiguous memory for pointers to the argument strings, and for the argument strings themselves; the calling application must free the memory used by the argument list when it is no longer needed. To free the memory, use a single call to the [LocalFree](https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-localfree) function.

-- https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw

File: src/main.cpp (hunk 1 above)
Comment (p2004a) [reply src/main.cpp]: No reason :), draft code :)

File: src/main.cpp (hunk 2 above)
Comment (p2004a) [reply src/main.cpp]: Ah, good catch, I've missed that, thank you!

**Comment by p2004a** [comment]
@rafidka Ok, I've cleaned up the code a bit, and tested more e2e and it works.

The issue is that it will not help you and your friend much in the end, as engine seems to have even worse state of handling unicode: https://github.com/beyond-all-reason/spring/issues/355
